plugins {
	// see https://fabricmc.net/develop/ for new versions
	id 'fabric-loom' version "${fabric_loom_version}" apply false
	// see https://projects.neoforged.net/neoforged/moddevgradle for new versions
	id 'net.neoforged.moddev' version "${neoforge_moddev_version}" apply false

	// Manual plugins added here
	id 'java'
	id "me.modmuss50.mod-publish-plugin" version "${mod_publish_version}"
}

// #####################################################################################
// # Convenience task that runs data gen for both NeoForge and Fabric (in that order). #
// #####################################################################################
tasks.register("runAllDatagen") {
	dependsOn(":neoforge:runData", ":fabric:runDatagen")
}

afterEvaluate {
	project(":fabric").afterEvaluate { fabricProject ->
		fabricProject.tasks.named("runDatagen").configure {
			mustRunAfter(":neoforge:runData")
		}
	}
}
// End
