# Done to increase the memory available to gradle.
org.gradle.jvmargs  = -Xmx4G
org.gradle.parallel = true

# Publishing Properties
cf_project_slug     = avp-regenesis
cf_id               = 1005026
modrinth_id         = Uqo0H9FX

# Fabric Properties https://fabricmc.net/develop
minecraft_version   = 1.21.1
loader_version      = 0.16.10
parchment_version   = 2024.11.17

# Mod Properties
mod_version         = 0.0.21-beta
maven_group         = com.avp
archives_base_name  = avp
mod_name            = Alien VS Predator
mod_description     = Adds a variety of content from both the Alien and Predator franchises!
mod_license         = CC0-1.0
mod_icon            = assets/avp/icon.png

# Dependencies
azurelib_version    = 3.0.11
fabric_version      = 0.115.0+1.21.1
modmenu_version     = 11.0.0
rei_version         = 16.0.799
architectury_version= 13.0.8
cloth_version       = 15.0.140
# versions found here: https://maven.su5ed.dev/#/releases/org/sinytra/item-asset-export-fabric
asset_export        = 1.0.2+1.21
# latest found here: https://maven.blamejared.com/mezz/jei/jei-1.21.1-fabric/maven-metadata.xml
jei_version         = 19.21.1.248