# Done to increase the memory available to gradle.
org.gradle.jvmargs   = -Xmx4G
org.gradle.parallel  = true

# Publishing Properties
cf_id                = 1005026
cf_project_slug      = avp
modrinth_id          = Uqo0H9FX

# Fabric Properties https://fabricmc.net/develop
loader_version       = 0.16.10
minecraft_version    = 1.21.1
parchment_version    = 2024.11.17

# Mod Properties
archives_base_name   = avp
maven_group          = com.avp
mod_description      = Adds a variety of content from both the Alien and Predator franchises!
mod_icon             = assets/avp/icon.png
mod_license          = Apache License 2.0
mod_name             = Alien VS Predator
mod_version          = 0.0.23-beta

# Dependencies
architectury_version = 13.0.8
# versions found here: https://maven.su5ed.dev/#/releases/org/sinytra/item-asset-export-fabric
asset_export         = 1.0.2+1.21
azurelib_version     = 3.0.11
cloth_version        = 15.0.140
fabric_version       = 0.115.0+1.21.1
# latest found here: https://maven.blamejared.com/mezz/jei/jei-1.21.1-fabric/maven-metadata.xml
jei_version          = 19.21.1.248
just_version         = 7edae6d449
modmenu_version      = 11.0.0
rei_version          = 16.0.799
