# Done to increase the memory available to gradle.
org.gradle.jvmargs            = -Xmx4G
org.gradle.caching            = true
org.gradle.daemon             = true
org.gradle.parallel           = true

# Mod Properties
version                       = 0.3.0-alpha.380
icon                          = assets/blib/icon.png
group                         = com.blib
java_version                  = 21

# Publishing Properties
cf_id                         = 1400219
cf_project_slug               = blib
dry_run                       = true
mod_publish_version           = 0.8.4
modrinth_id                   = RWbP2zLp

# Maven Publishing Properties
maven_url                     = https://maven.bvanseghi.dev/blib/

# Common
minecraft_version             = 1.21.1
mod_name                      = BLib
mod_author                    = Stargazer Studios
mod_id                        = blib
license                       = All Rights Reserved
credits                       = Stargazer Studios
description                   = A library that makes multi-loader mod development more streamlined.
minecraft_version_range       = [1.21.1, 1.22)
mixin_version                 = 0.8.5
mixinextras_common_version    = 0.3.5
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version              = 1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft           = 1.21.1
parchment_version             = 2024.11.17

# Fabric
fabric_loader_version         = 0.18.4
fabric_loom_version           = 1.14-SNAPSHOT
fabric_version                = 0.116.7+1.21.1

# NeoForge
neoforge_loader_version_range = [4,)
neoforge_moddev_version       = 2.0.137
neoforge_version              = 21.1.217

# Plugins
foojay_resolver_version       = 1.0.0
spotless_version              = 8.1.0
ben_manes_versions_version    = 0.53.0

# Dependencies
just_codec_version            = 0.1.0
just_core_version             = 0.1.0
just_goap_version             = 0.4.0
logback_classic_version       = 1.4.11
slf4j_version                 = 2.0.9

# Test Dependencies
architectury_version          = 13.0.8
cloth_version                 = 15.0.140
emi_version                   = 1.1.22+1.21.1
# latest found here: https://maven.blamejared.com/mezz/jei/jei-1.21.1-fabric/maven-metadata.xml
jei_version                   = 19.21.1.248
modmenu_version               = 11.0.0
rei_version                   = 16.0.799

# Control Variables
recipe_viewer                 = rei
