package com.blib.engine.modeler.item;

import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemDisplayContext;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import com.blib.api.client.render.v1.BLibTransform;
import com.blib.api.client.render.v1.item.BLibItemTransformMode;
import com.blib.engine.gizmo.BLibItemTransformOverrides;

/**
 * Java-snippet dump of {@link BLibItemTransformOverrides} state for an item, intended for paste-back into a renderer's
 * {@code BLibItemTransforms.builder()} constants. Used by the Modeler's "Dump as Java" button in the Item Config
 * inspector section.
 */
@ApiStatus.Internal
public final class ItemTransformDump {

    private ItemTransformDump() {}

    /**
     * Write the current effective transforms for {@code itemId} to a Java-snippet file under the game dir's
     * {@code blib_transform_dumps/} folder. Returns the dump path on success, {@code null} when the item has no
     * effective transforms to dump. Throws {@link IOException} on write failure.
     */
    public static @Nullable Path dump(ResourceLocation itemId) throws IOException {
        var idleEffective = collectEffectiveTransforms(itemId, BLibItemTransformMode.IDLE);
        var blockingEffective = collectEffectiveTransforms(itemId, BLibItemTransformMode.BLOCKING);
        var idleWallFixed = BLibItemTransformOverrides.getWallFixed(itemId, BLibItemTransformMode.IDLE);
        var blockingWallFixed = BLibItemTransformOverrides.getWallFixed(itemId, BLibItemTransformMode.BLOCKING);

        if (idleEffective.isEmpty() && blockingEffective.isEmpty() && idleWallFixed == null && blockingWallFixed == null) {
            return null;
        }

        var content = formatDumpFile(itemId, idleEffective, blockingEffective, idleWallFixed, blockingWallFixed);
        var dumpPath = resolveDumpPath(itemId);
        Files.createDirectories(dumpPath.getParent());
        Files.writeString(dumpPath, content);
        return dumpPath;
    }

    private static Map<ItemDisplayContext, BLibTransform> collectEffectiveTransforms(ResourceLocation itemId, BLibItemTransformMode mode) {
        // Mode-specific lookup (no cascade): only emit contexts explicitly set in this mode's override or base.
        // The renderer's runtime cascade handles missing contexts at draw time; emitting them here would corrupt
        // the per-context override semantics on paste-back.
        var result = new LinkedHashMap<ItemDisplayContext, BLibTransform>();
        for (var context : ItemDisplayContext.values()) {
            if (context == ItemDisplayContext.NONE) {
                continue;
            }
            var modeValue = BLibItemTransformOverrides.getModeValueOrNull(itemId, mode, context);
            if (modeValue == null) {
                continue;
            }
            if (modeValue.equals(BLibTransform.IDENTITY)) {
                continue;
            }
            result.put(context, modeValue);
        }
        return result;
    }

    private static Path resolveDumpPath(ResourceLocation itemId) {
        var safeName = (itemId.getNamespace() + "__" + itemId.getPath()).replaceAll("[^A-Za-z0-9_]", "_");
        return Minecraft.getInstance().gameDirectory.toPath().toAbsolutePath().resolve("blib_transform_dumps").resolve(safeName + ".java");
    }

    private static String formatDumpFile(
        ResourceLocation itemId,
        Map<ItemDisplayContext, BLibTransform> idle,
        Map<ItemDisplayContext, BLibTransform> blocking,
        @Nullable BLibTransform idleWallFixed,
        @Nullable BLibTransform blockingWallFixed
    ) {
        var timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        var sb = new StringBuilder();
        sb.append("// Generated by the BLib Modeler item-config dump\n");
        sb.append("// Item: ").append(itemId).append('\n');
        sb.append("// Timestamp: ").append(timestamp).append('\n');
        sb.append("// Paste each block over the corresponding constant in your renderer.\n\n");

        if (!idle.isEmpty() || idleWallFixed != null) {
            sb.append("// IDLE\n");
            sb.append("BLibItemTransforms.builder()\n");
            for (var entry : idle.entrySet()) {
                sb.append("    ").append(formatJavaLine(entry.getKey(), entry.getValue())).append('\n');
            }
            if (idleWallFixed != null) {
                sb.append("    ").append(formatWallFixedJavaLine(idleWallFixed)).append('\n');
            }
            sb.append("    .build();\n");
        }

        if (!blocking.isEmpty() || blockingWallFixed != null) {
            if (!idle.isEmpty() || idleWallFixed != null) {
                sb.append('\n');
            }
            sb.append("// BLOCKING\n");
            sb.append("BLibItemTransforms.builder()\n");
            for (var entry : blocking.entrySet()) {
                sb.append("    ").append(formatJavaLine(entry.getKey(), entry.getValue())).append('\n');
            }
            if (blockingWallFixed != null) {
                sb.append("    ").append(formatWallFixedJavaLine(blockingWallFixed)).append('\n');
            }
            sb.append("    .build();\n");
        }

        return sb.toString();
    }

    private static String formatJavaLine(ItemDisplayContext context, BLibTransform t) {
        var builderMethod = builderMethodFor(context);
        var scaleStr = formatScale(t);
        var pivotX = t.pivot().x;
        var pivotY = t.pivot().y;
        var pivotZ = t.pivot().z;
        var hasPivot = pivotX != 0 || pivotY != 0 || pivotZ != 0;
        if (hasPivot) {
            return ".%s(BLibTransform.of(%sf, %sf, %sf, %sf, %sf, %sf, %s, %sf, %sf, %sf))".formatted(
                builderMethod,
                formatFloat(t.translation().x),
                formatFloat(t.translation().y),
                formatFloat(t.translation().z),
                formatFloat(t.rotation().x),
                formatFloat(t.rotation().y),
                formatFloat(t.rotation().z),
                scaleStr,
                formatFloat(pivotX),
                formatFloat(pivotY),
                formatFloat(pivotZ)
            );
        }
        return ".%s(BLibTransform.of(%sf, %sf, %sf, %sf, %sf, %sf, %s))".formatted(
            builderMethod,
            formatFloat(t.translation().x),
            formatFloat(t.translation().y),
            formatFloat(t.translation().z),
            formatFloat(t.rotation().x),
            formatFloat(t.rotation().y),
            formatFloat(t.rotation().z),
            scaleStr
        );
    }

    private static String formatWallFixedJavaLine(BLibTransform t) {
        var scaleStr = formatScale(t);
        var pivotX = t.pivot().x;
        var pivotY = t.pivot().y;
        var pivotZ = t.pivot().z;
        var hasPivot = pivotX != 0 || pivotY != 0 || pivotZ != 0;
        if (hasPivot) {
            return ".fixedWall(BLibTransform.of(%sf, %sf, %sf, %sf, %sf, %sf, %s, %sf, %sf, %sf))".formatted(
                formatFloat(t.translation().x),
                formatFloat(t.translation().y),
                formatFloat(t.translation().z),
                formatFloat(t.rotation().x),
                formatFloat(t.rotation().y),
                formatFloat(t.rotation().z),
                scaleStr,
                formatFloat(pivotX),
                formatFloat(pivotY),
                formatFloat(pivotZ)
            );
        }
        return ".fixedWall(BLibTransform.of(%sf, %sf, %sf, %sf, %sf, %sf, %s))".formatted(
            formatFloat(t.translation().x),
            formatFloat(t.translation().y),
            formatFloat(t.translation().z),
            formatFloat(t.rotation().x),
            formatFloat(t.rotation().y),
            formatFloat(t.rotation().z),
            scaleStr
        );
    }

    private static String formatScale(BLibTransform t) {
        var scaleX = t.scale().x;
        var scaleEqual = scaleX == t.scale().y && t.scale().y == t.scale().z;
        if (scaleEqual) {
            return formatFloat(scaleX) + "f";
        }
        return "/* non-uniform " + formatFloat(t.scale().x) + "/" + formatFloat(t.scale().y) + "/" + formatFloat(t.scale().z) + " */ "
            + formatFloat(scaleX) + "f";
    }

    private static String builderMethodFor(ItemDisplayContext context) {
        return switch (context) {
            case GUI -> "gui";
            case GROUND -> "ground";
            case FIXED -> "fixed";
            case HEAD -> "head";
            case FIRST_PERSON_LEFT_HAND -> "firstPersonLeftHand";
            case FIRST_PERSON_RIGHT_HAND -> "firstPersonRightHand";
            case THIRD_PERSON_LEFT_HAND -> "thirdPersonLeftHand";
            case THIRD_PERSON_RIGHT_HAND -> "thirdPersonRightHand";
            case NONE -> "/* NONE — handle via .set(ItemDisplayContext.NONE, ...) */ ";
        };
    }

    private static String formatFloat(float v) {
        var s = String.format(Locale.ROOT, "%.4f", v);
        if (s.contains(".")) {
            s = s.replaceAll("0+$", "");
            if (s.endsWith(".")) {
                s = s + "0";
            }
        }
        return s;
    }
}
